# Generated by Django 5.0.14 on 2026-09-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('version', models.CharField(default='Latest', max_length=30)),
                ('monaco_id', models.CharField(default='plaintext', help_text='Monaco language identifier (e.g. python, cpp, javascript, java)', max_length=30)),
                ('file_extension', models.CharField(default='.txt', max_length=15)),
                ('default_filename', models.CharField(default='main.txt', max_length=100)),
                ('default_code', models.TextField(blank=True, default='')),
                ('compile_command', models.CharField(blank=True, help_text='Optional compilation command', max_length=255)),
                ('run_command', models.CharField(help_text='Command or runner key to execute the code', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('supports_stdin', models.BooleanField(default=True)),
                ('supports_debugging', models.BooleanField(default=False)),
                ('formatter_name', models.CharField(blank=True, default='standard', max_length=50)),
                ('icon_name', models.CharField(default='file-code', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
