# Generated by Django 5.0.14 on 2026-09-23 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('codeforge-dark', 'CodeForge Dark'), ('vs-dark', 'VS Dark'), ('midnight', 'Midnight High Contrast'), ('vs-light', 'Light Mode')], default='codeforge-dark', max_length=50)),
                ('font_size', models.PositiveIntegerField(default=14)),
                ('tab_size', models.PositiveIntegerField(default=4)),
                ('word_wrap', models.BooleanField(default=True)),
                ('minimap', models.BooleanField(default=True)),
                ('autocomplete', models.BooleanField(default=True)),
                ('bracket_matching', models.BooleanField(default=True)),
                ('line_numbers', models.BooleanField(default=True)),
                ('keybinding', models.CharField(choices=[('standard', 'Standard'), ('vim', 'Vim'), ('emacs', 'Emacs')], default='standard', max_length=20)),
                ('cursor_style', models.CharField(default='line', max_length=20)),
                ('terminal_font_size', models.PositiveIntegerField(default=13)),
                ('autosave_enabled', models.BooleanField(default=True)),
                ('autosave_delay_ms', models.PositiveIntegerField(default=1500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar_url', models.URLField(blank=True)),
                ('github_handle', models.CharField(blank=True, max_length=100)),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
