# Generated by Django 5.0.14 on 2026-09-23 07:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('stdin', models.TextField(blank=True, default='')),
                ('command_args', models.CharField(blank=True, default='', max_length=255)),
                ('compiler_flags', models.CharField(blank=True, default='', max_length=255)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='languages.language')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('exit_code', models.IntegerField(default=0)),
                ('memory_bytes', models.BigIntegerField(default=0)),
                ('status_message', models.CharField(blank=True, default='Process finished successfully.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='executions.execution')),
            ],
        ),
    ]
